import zanon
import pandas as pd
import datetime

# Exception: filename_in = "cent_w_comm_zanon_z_" + str(1) + "_dt_7260_nGw_5_distSm_normal_maxSm_100_seed_1" #+ str(seed)

def preprocess_log_data_for_zanon(input_path, input_file, jha_input_path):
    df_in = pd.read_csv( (input_path + input_file), sep =",")
    df_in = df_in#.iloc[0:2000]
    print(df_in.head())

    # convert timestamps to unix timestamps
    l_time = [(datetime.datetime.strptime(t, "%Y-%m-%d %H:%M:%S")).timestamp() for t in df_in["time"] ]
    print(l_time[0:5])
    df_in.loc[:, "time"] = l_time
    print(df_in.head())

    # store data used for Jha zanon 
    # work with bucketed values
    jha_data = pd.DataFrame({"time": df_in["time"], "ID": df_in["ID"], "value": df_in["value"]})
    jha_data_filename = ( "jha_" + input_file)
    jha_data.to_csv( (jha_input_path + jha_data_filename), sep=",", index = False, header=False)
    print(jha_data_filename)
    print(jha_data.head())

    # return filename for further simulation
    return jha_data_filename


####################
####################
# compare output generated by centralized deZent and implementation by Jha et al.
input_path = "./data/log_data/deZent/" 
jha_input_path = "./data/log_data/jha/"
anon_path = "./data/anonymized_data/jha/"

deltat = 7260 #in seconds
l_n_gw = [5] #, 25, 50, 75, 100, 125, 150] 

prefix = "simu_log_"
dez_scenario = "cent_w_comm_zanon_z_"

for n_gw in l_n_gw:
    scenario_params = "_dt_" + str(deltat) + "_nGw_" + str(n_gw) + "_distSm_normal_maxSm_20"


    for seed in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
        for z_val in [1, 5, 10, 25, 50, 100]:

            scenario = dez_scenario + str(z_val) + scenario_params + "_seed_" + str(seed)
            input_filename = prefix + scenario 
            input_file = input_filename + ".csv"

            input_for_jha = preprocess_log_data_for_zanon(input_path, input_file, jha_input_path)

            z = zanon.zanon(deltat, z_val, anon_path, input_for_jha)
            print("zanon files")
            print(input_for_jha + "\n")
            for line in open( (jha_input_path + input_for_jha), 'r'):
                t,u,a = line.split(",")
                z.anonymize((t,u,a))
            z.endFiles()
            z.duration()



